apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demoapp-16 #dev-aks-cluster
  annotations:
    github.com/project-slug: rohit7533/terraform-aks
    terraform/workspaces: NodeJSAks
    terraform/organization: kedar-org
  description: Azure Kubernetes Service(AKS) cluster managed by Terraform
  tags:
    - azure
    - aks
    - terraform
spec:
  type: service
  owner: "rohit7533"
  lifecycle: production
